version: '3.8'

services:
  pythonapp:
    image: python/app:3
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 4000:4532

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pythonapp_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: pgadmin/pgadmin4
    restart: always
    depends_on:
      - postgres
    env:


#   web:
#     build: .
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_NAME=pythonapp_database
#       - DB_USER=postgres
#       - DB_PASS=password
#     volumes:
#       - .:/app
#     depends_on:
#       - db

# volumes:
#   pgdata: